spring:
  application:
    name: Ink3-AUTH

server:
  port: 10256

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always
    eureka:
      enabled: false
    redis:
      enabled: false

