spring:
  cloud:
    openfeign:
      client:
        config:
          user-api:
            url: http://localhost:8080
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
jwt:
  private-key-path: classpath:secret/private.pem
  public-key-path: classpath:secret/public.pem
  access-token-validity: 1800000
  refresh-token-validity: 604800000
