name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from POM
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 추출된 버전 확인
        run: echo "${{ steps.extract_version.outputs.version }} 입니다."

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Generate dummy JWT keys
        run: |
          mkdir -p secret
          echo "-----BEGIN PRIVATE KEY-----" > secret/private.pem
          echo "FAKE-KEY-DATA" >> secret/private.pem
          echo "-----END PRIVATE KEY-----" >> secret/private.pem
          
          echo "-----BEGIN PUBLIC KEY-----" > secret/public.pem
          echo "FAKE-KEY-DATA" >> secret/public.pem
          echo "-----END PUBLIC KEY-----" >> secret/public.pem
          
          echo "JWT_PRIVATE_KEY_PATH=$PWD/secret/private.pem" >> $GITHUB_ENV
          echo "JWT_PUBLIC_KEY_PATH=$PWD/secret/public.pem" >> $GITHUB_ENV

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with coverage
        run: mvn clean verify -B -DJWT_PRIVATE_KEY_PATH=$JWT_PRIVATE_KEY_PATH -DJWT_PUBLIC_KEY_PATH=$JWT_PUBLIC_KEY_PATH

  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Generate dummy JWT keys for test
        run: |
          mkdir -p secret
          echo "-----BEGIN PRIVATE KEY-----" > secret/private.pem
          echo "MIIBVA..." >> secret/private.pem
          echo "-----END PRIVATE KEY-----" >> secret/private.pem

          echo "-----BEGIN PUBLIC KEY-----" > secret/public.pem
          echo "MFwwDQ..." >> secret/public.pem
          echo "-----END PUBLIC KEY-----" >> secret/public.pem

      - name: SonarQube Scan
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=ink3_auth_server \
            -Dsonar.projectName='ink3_auth_server' \
            -Dsonar.host.url=http://s4.java21.net:9000 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Check coverage threshold
        run: |
          LINE_COVERAGE=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+' | paste -sd+ - | bc)
          LINE_MISSED=$(grep -A1 "<counter type=\"LINE\"" target/site/jacoco/jacoco.xml | grep -oP 'missed="\K[0-9]+' | paste -sd+ - | bc)
          TOTAL=$((LINE_COVERAGE + LINE_MISSED))
          PERCENT=$((LINE_COVERAGE * 100 / TOTAL))
          echo "Coverage: $PERCENT%"
#          if [ "$PERCENT" -lt 60 ]; then
#            echo "Coverage is below 60%! Failing build."
#            exit 1
#          fi

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Generate dummy JWT keys for test
        run: |
          mkdir -p secret
          echo "-----BEGIN PRIVATE KEY-----" > secret/private.pem
          echo "MIIBVA..." >> secret/private.pem
          echo "-----END PRIVATE KEY-----" >> secret/private.pem
          
          echo "-----BEGIN PUBLIC KEY-----" > secret/public.pem
          echo "MFwwDQ..." >> secret/public.pem
          echo "-----END PUBLIC KEY-----" >> secret/public.pem

      - name: Extract version from POM
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 추출된 버전 확인
        run: echo "${{ steps.extract_version.outputs.version }} 입니다."

      - name: Package application (skip tests)
        run: mvn package -DskipTests=true -B

      - name: Run application in background
        env:
          EUREKA_URL: ${{ secrets.EUREKA_URL }}
        run: |
          nohup java -jar target/ink3-auth-${{ steps.extract_version.outputs.version }}.jar --server.port=10256 > app.log 2>&1 &
          echo $! > app.pid

      - name: Wait for application to start
        run: sleep 15

      - name: Check JAR file exists
        run: ls -lh target/ink3-auth-${{ steps.extract_version.outputs.version }}.jar

      - name: Check health endpoint
        run: curl --fail http://localhost:10256/actuator/health

      - name: Stop application
        run: kill $(cat app.pid)

      - name: Run unit tests
        env:
          EUREKA_URL: ${{ secrets.EUREKA_URL }}
        run: mvn test -B

      - name: Print app log if health check fails
        if: failure()
        run: cat app.log

  deploy:
    name: Deploy to Linux Server
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR (skip tests)
        run: mvn package -DskipTests=true -B

      - name: Verify JAR file
        run: ls -lh target/*.jar

      - name: Extract version from POM
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 추출된 버전 확인
        run: echo "${{ steps.extract_version.outputs.version }} 입니다."

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.jar"
          target: "~/ink3-server/auth"

      - name: Write key files
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > private.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > public.pem

      - name: Send keys to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          source: "private.pem,public.pem"
          target: "~/ink3-server/auth/secret"

      - name: Run deploy.sh on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/ink3-server/auth
            chmod +x deploy.sh
            export EUREKA_URL=${{ secrets.EUREKA_URL }}
            export JWT_PRIVATE_KEY_PATH=${{ secrets.JWT_PRIVATE_KEY_PATH }}
            export JWT_PUBLIC_KEY_PATH=${{ secrets.JWT_PUBLIC_KEY_PATH }}
            nohup ./deploy.sh "${{ steps.extract_version.outputs.version }}" > deploy.log 2>&1 &
            exit 0
